gframework.usermessage = {}
gframework.umsg = gframework.usermessage

UMSG_TYPE_END = -1
UMSG_TYPE_STOP = 0
UMSG_TYPE_STRING = 1
UMSG_TYPE_UNFINISHED_STRING = 2
UMSG_TYPE_NUMBER = 3
UMSG_TYPE_VECTOR = 4
UMSG_TYPE_ANGLE = 5
UMSG_TYPE_BOOL = 6
UMSG_TYPE_CHAR = 7
UMSG_TYPE_ENTITY = 8
UMSG_TYPE_COLOR = 9
UMSG_TYPE_PHYSOBJ = 10
UMSG_TYPE_NIL = 11